#!/usr/bin/env bash
# Install load balancer
sudo apt update
sudo apt install -y haproxy
sudo chmod 777 /etc/haproxy/
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_backup.cfg
echo -e "frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend web_backend\n" >> /etc/haproxy/haproxy.cfg
echo -e "backend web_backend\n\tbalance roundrobin\n\tserver 4640-web-01 34.224.30.90:80 check\n\tserver 4640-web-02 54.197.191.211:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

