#!/usr/bin/env bash
# This is a script for task 4
# hostname -I
# Display the IP address of the host

if [ "$1" == "" ]
then
    echo "5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 $1
fi
