#!/usr/bin/env bash
# install firewall
sudo apt-get -y update
sudo apt-get -y install ufw
sudp ufw allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
